services:
  postgres:
    image: postgres:16-alpine
    container_name: sheltr_db
    restart: always
    environment:
      POSTGRES_USER: sheltr
      POSTGRES_PASSWORD: sheltr
      POSTGRES_DB: sheltr
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb

volumes:
  pgdata: